version: "3"
services:
    db:
        build: ./docker/mysql
        ports:
            - "33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: test_db
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    php:
        build: ./docker/php
        privileged: true
        command: /sbin/init
        volumes:
            - ./src/:/var/www/
    #    depends_on:
    #        - db
        ports:
            - "8080:80"